# name: Generate PDF from HTML

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'index.html'
#       - 'generate-pdf.js'
#   workflow_dispatch:

# jobs:
#   build-pdf:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18' # Or your preferred Node.js version

#       - name: Install Puppeteer and dependencies
#         run: |
#           npm install puppeteer
#           # Install other necessary dependencies for Puppeteer on Linux
#           # sudo apt-get update
#           # sudo apt-get install -yq libgconf-2-4 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
#           # libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
#           # libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
#           # libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
#           # ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev

#       - name: Run PDF generation script
#         run: node generate-pdf.js

#       - name: Commit and push PDF
#         run: |
#           git config --global user.name 'github-actions[bot]'
#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#           git pull origin main --rebase # Pull latest changes before committing
#           git add assets/4rgon4ut.pdf
#           # Check if there are changes to commit
#           if ! git diff --staged --quiet; then
#             git commit -m "docs: Generate and update PDF from index.html [skip ci]"
#             git push
#           else
#             echo "No changes to PDF, skipping commit."
#           fi
