# name: Convert HTML to PDF

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch: # allows manual trigger of the action

# jobs:
#   convert-html:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Run the HTML to PDF converter action
#       - name: HTML website to PDF converter
#         uses: ferdinandkeller/html-to-pdf-action@v2
#         with:
#           source-path: "."
#           destination-path: "./assets/4rgon4ut.pdf"

#       # Upload the PDF as an artifact
#       - name: Upload PDF
#         uses: actions/upload-artifact@v4
#         with:
#           name: generated-pdf
#           path: ./assets/4rgon4ut.pdf